inherit_from:
  - https://gitlab.com/bsm/misc/raw/master/rubocop/default.yml

AllCops:
  TargetRubyVersion: 2.4

Naming/MemoizedInstanceVariableName:
  Enabled: false
Naming/FileName:
  Exclude: [lib/sortable-by.rb]
