AllCops:
  TargetRubyVersion: 2.2

Metrics/AbcSize:
  Enabled: false
Naming/FileName:
  Exclude: [lib/sortable-by.rb]
Metrics/MethodLength:
  Max: 20
Metrics/LineLength:
  Max: 120

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
